---
- name: Install dev binaries and dependencies
  apt: 
    name:           "{{ packages }}"
    state:          present
    update_cache:   yes
    autoremove:     yes
    force_apt_get:  yes
  vars:
    packages:
    - acl
    - ansible
    - sshpass
    - git
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - python3-appdirs
    - python3-distlib
    - python3-filelock
    - libffi-dev
    - libssl-dev
    - gcc
  become:           true
